# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6124048342b30dc0096bf71a31f4659d39ad1fa619af0bc47a76480109a4a14a91dfcea25cf6a5a88c7ae764e27fe25dd0f5223edbd5ee1182e17a00e9c9126b

test:
  secret_key_base: ad2d0c0c10c72351e709774d506e86a15d14280fcab07c4ac280c13fabccc77caa98a0af341e0cace7d1adee0af905789f5933d8595b0a45d8d7c999d46a5c68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
